backend:
  name: git-gateway
  branch: main

media_folder: static/img
public_folder: /img

collections:
  - label: 'Pages'
    name: 'pages'
    format: 'frontmatter'
    files:
      - label: 'Home Page'
        name: 'home'
        file: 'content/home.md'
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Sub title, name: subTitle, widget: string }
          - { label: Email, name: email, widget: string }

      - label: 'About Page'
        name: 'about'
        file: 'content/about.md'
        fields:
          - { label: Title, name: title, widget: string }
          - { label: About text, name: aboutText, widget: markdown }
          - { label: About image, name: image, widget: image }
          - label: IT skills
            name: skills
            widget: list
            fields:
              - { label: skill, name: skill, widget: string }

  - label: 'Portfolio'
    name: 'portfolio'
    folder: 'content/portfolio'
    format: 'frontmatter'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
    preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: Portfolio image, name: portfolioImage, widget: image }
      - { label: 'GitHub link', name: 'gitHubLink', widget: 'string', required: false }
      - { label: 'Site link', name: 'siteLink', widget: 'string', required: false }
      - label: Tech list
        name: techList
        widget: list
        fields:
          - { label: Tech used, name: techUsed, widget: string }
